"""Freeze a fresh SHA-bound binding for the authorized E04-E V2 run."""
from __future__ import annotations
import argparse,json,secrets,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from scripts.e04_e_equal_slot_execution import ARMS,BASE,JOINT_CAP_SECONDS,PER_ARM_CAP_SECONDS,atomic_json,relative,sha_path,static_schedule_preflight
RESPONSE=ROOT/'orchestration/director/responses/E04_E_V2_RUN_001_OOM_RESULT_AND_REPLACEMENT_AUTHORIZATION_BRIEF_RESPONSE.json'
WORKER=ROOT/'scripts/run_e04_e_equal_slot_marker_replay_pilot.py';EVALUATOR=ROOT/'scripts/score_e04_e_equal_slot_marker_replay_pilot.py';LAUNCHER=ROOT/'scripts/launch_e04_e_equal_slot_marker_replay_pilot.py';LOSS=ROOT/'scripts/e04_e_equal_slot_loss.py';LOSS_TEST=ROOT/'tests/test_e04_e_equal_slot_loss.py'
CONFIG='experiments/capability_repair_baseline_v1/e04_orientation_fixed_demonstration_baseline_v3/E04_V3_FULL768_B1_NO_UPDATE_REMEASUREMENT_V1_CONFIG.json';V7='experiments/capability_repair_baseline_v1/e04_orientation_fixed_demonstration_baseline_v3/e04_v3_full768_b1_no_update_remeasurement_v1/run_001_2ee668738df64d558f666f5989d09add/PRIMARY_B1_RAW.jsonl'
def main():
 p=argparse.ArgumentParser();p.add_argument('--output',type=Path,required=True);p.add_argument('--run-root-prefix',default='/workspace/arc2/e04_e_equal_slot_weight_marker_replay_preservation_pilot_v2');p.add_argument('--worker-source-commit');p.add_argument('--run-id',default='RUN_002');a=p.parse_args()
 if a.output.exists():raise SystemExit('E04E_BINDING_REFUSE_OVERWRITE')
 proof=static_schedule_preflight();response=json.loads(RESPONSE.read_text())
 auth=response.get('execution_authorization',{})
 if response.get('response_id')!='E04_E_V2_RUN_001_OOM_RESULT_AND_REPLACEMENT_AUTHORIZATION_BRIEF_RESPONSE' or response.get('decision')!='CONTINUE_CONTROLLER' or a.run_id!='RUN_002' or not(auth.get('gpu_training_authorized_after_all_gates') and auth.get('post_training_physical_b1_native_greedy_generation_authorized') and auth.get('post_freeze_cpu_scoring_authorized') and auth.get('maximum_detached_jobs')==1 and auth.get('authorized_run')=='RUN_002' and auth.get('arm_names')==list(ARMS) and auth.get('per_arm_runtime_cap_seconds')==PER_ARM_CAP_SECONDS and auth.get('joint_runtime_cap_seconds')==JOINT_CAP_SECONDS):raise SystemExit('E04E_DIRECTOR_AUTH')
 source=a.worker_source_commit or subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip();nonce=secrets.token_hex(16);out=a.run_root_prefix.rstrip('/')+'/'+a.run_id.lower()+'_'+nonce
 b={'schema_version':1,'protocol_id':proof['protocol_id'],'authorization_id':response['response_id'],'director_response_path':relative(RESPONSE),'director_response_sha256':sha_path(RESPONSE),'execution_authorized':True,'worker_source_commit':source,'worker_path':relative(WORKER),'worker_sha256':sha_path(WORKER),'evaluator_path':relative(EVALUATOR),'evaluator_sha256':sha_path(EVALUATOR),'launcher_path':relative(LAUNCHER),'launcher_sha256':sha_path(LAUNCHER),'loss_path':relative(LOSS),'loss_sha256':sha_path(LOSS),'cpu_loss_test_path':relative(LOSS_TEST),'cpu_loss_test_sha256':sha_path(LOSS_TEST),'protocol_path':relative(BASE/'E04_E_V2_PRELAUNCH_PROTOCOL.json'),'protocol_sha256':sha_path(BASE/'E04_E_V2_PRELAUNCH_PROTOCOL.json'),'control_schedule_path':relative(BASE/'CONTROL_SCHEDULE.json'),'control_schedule_sha256':sha_path(BASE/'CONTROL_SCHEDULE.json'),'treatment_schedule_path':relative(BASE/'TREATMENT_SCHEDULE.json'),'treatment_schedule_sha256':sha_path(BASE/'TREATMENT_SCHEDULE.json'),'token_accounting_path':relative(BASE/'TOKEN_ACCOUNTING.json'),'token_accounting_sha256':sha_path(BASE/'TOKEN_ACCOUNTING.json'),'checkpoint_manifest_path':'experiments/capability_repair_baseline_v1/CHECKPOINT_MANIFEST_REMOTE_V1.json','checkpoint_manifest_sha256':sha_path(ROOT/'experiments/capability_repair_baseline_v1/CHECKPOINT_MANIFEST_REMOTE_V1.json'),'runtime_config_path':CONFIG,'runtime_config_sha256':sha_path(ROOT/CONFIG),'v7_reference_raw_path':V7,'v7_reference_raw_sha256':sha_path(ROOT/V7),'arm_order':list(ARMS),'seed':2000031,'arms':2,'jobs':1,'retry':False,'nonce':nonce,'output_root':out,'arm_output_roots':{arm:out+'/arms/'+arm for arm in ARMS},'per_arm_runtime_cap_seconds':PER_ARM_CAP_SECONDS,'joint_runtime_cap_seconds':JOINT_CAP_SECONDS,'static_preflight':proof}
 atomic_json(a.output,b);print(json.dumps({'status':'FRESH_E04E_BINDING_CREATED','binding_sha256':sha_path(a.output),'nonce':nonce,'worker_source_commit':source},sort_keys=True))
if __name__=='__main__':main()
