"""Machine-readable, versioned primitive capability registry."""
from __future__ import annotations
from dataclasses import asdict, dataclass
import importlib

REQUIRED_FIELDS={'primitive_id','version','human_name','category','input_types','output_types','parameters','preconditions','exact_semantics','failure_conditions','preserves','does_not_do','deterministic','implementation_reference'}
@dataclass(frozen=True)
class PrimitiveSpec:
    primitive_id:str; version:str; human_name:str; category:str; input_types:list[str]; output_types:list[str]; parameters:dict; preconditions:str; exact_semantics:str; failure_conditions:str; preserves:str; does_not_do:str; deterministic:bool; implementation_reference:str; complexity_cost:int=1
    def json(self): return asdict(self)
def _s(identifier,category,reference,parameters=None,semantics='Deterministic operation with the documented parameters.'):
    return PrimitiveSpec(identifier,'v1',identifier,category,['ARCGrid','ARCObject'],['ARCGrid','ARCObject','bool','number'],parameters or {},'Inputs satisfy declared types.',semantics,'Invalid parameters, ambiguity, or boundary violation returns INVALID.','Only documented fields.','No inference beyond its explicit semantics.',True,reference)
_BASE=[
 _s('GRID_IDENTITY_V0','transform','transforms.core.Identity'),_s('GRID_ROTATE90_V0','transform','transforms.core.Rotate',{'degrees':90}),_s('GRID_ROTATE180_V0','transform','transforms.core.Rotate',{'degrees':180}),_s('GRID_ROTATE270_V0','transform','transforms.core.Rotate',{'degrees':270}),_s('GRID_FLIP_HORIZONTAL_V0','transform','transforms.core.FlipHorizontal'),_s('GRID_FLIP_VERTICAL_V0','transform','transforms.core.FlipVertical'),_s('GRID_TRANSPOSE_V0','transform','transforms.core.Transpose'),_s('GRID_ANTI_TRANSPOSE_V0','transform','transforms.core.AntiTranspose'),_s('GRID_RECOLOR_V0','transform','solvers.library_v0.ColorMapProgram'),_s('GRID_FIXED_CROP_V0','transform','solvers.library_v0.FixedCropProgram'),_s('GRID_FOREGROUND_BBOX_CROP_V0','transform','solvers.library_v0.ForegroundBBoxProgram'),_s('GRID_TRANSLATE_FOREGROUND_V0','transform','solvers.library_v0.TranslationProgram'),
]
_SELECT=[_s(f'SEL_{name.upper()}_V1','selection','representations.selectors.ObjectSelector',{'selector':name}) for name in ('largest','smallest','unique_area','unique_shape','unique_color','border','non_border')]
_REL=[
 ('REL_SAME_COLOR_V1','same_color'),('REL_SAME_AREA_V1','same_area'),('REL_SAME_BBOX_SIZE_V1','same_bbox_size'),('REL_SAME_SHAPE_V1','same_shape'),('REL_ROTATED_EQUIVALENT_V1','rotated_equivalent'),('REL_REFLECTED_EQUIVALENT_V1','reflected_equivalent'),('REL_LEFT_OF_V1','left_of'),('REL_RIGHT_OF_V1','right_of'),('REL_ABOVE_V1','above'),('REL_BELOW_V1','below'),('REL_ROW_ALIGNED_CENTER_V1','row_aligned_center'),('REL_COLUMN_ALIGNED_CENTER_V1','column_aligned_center'),('REL_OVERLAP_V1','overlap'),('REL_CONTAINS_BBOX_V1','contains_bbox'),('REL_INSIDE_BBOX_V1','inside_bbox'),('DIST_MANHATTAN_MIN_V1','min_manhattan'),('DIST_CHEBYSHEV_MIN_V1','min_chebyshev'),('DIST_BBOX_CENTER_EUCLIDEAN_V1','bbox_center_euclidean'),('SEL_UNIQUE_NEAREST_V1','unique_nearest'),('SEL_UNIQUE_FARTHEST_V1','unique_farthest')]
_REL_SPECS=[_s(identifier,'relation','representations.relations_v1.'+fn) for identifier,fn in _REL]+[_s('REL_TOUCHING_4_V1','relation','representations.relations_v1.touching_4',semantics='True iff a pixel pair is 4-neighbour adjacent; diagonal-only contact, bbox overlap, and shared row/column are false.')]
_OPS=[_s('SEL_RELATIONAL_V1','selection','primitives.program.select_relational',{'kind':'touching_unique|non_touching_unique|same_shape_unique|different_shape_unique|row_aligned_unique|column_aligned_unique|nearest|farthest','reference_selector':'optional','role':'selected|reference|a|b'}),_s('OBJ_CROP_V1','render','representations.object_ops.crop_object'),_s('OBJ_RECOLOR_V1','render','representations.object_ops.recolor_object',{'color':'0..9'}),_s('OBJ_REMOVE_V1','render','representations.object_ops.remove_object'),_s('OBJ_MOVE_V1','render','representations.object_ops.render_object',{'dr':'int','dc':'int','copy':False}),_s('OBJ_COPY_V1','render','representations.object_ops.render_object',{'dr':'int','dc':'int','copy':True}),_s('ALIGN_EDGE_V1','composition','primitives.program.align_object',{'edge':'top|bottom|left|right|center_row|center_column','collision':'overwrite'}),_s('COMP_MASK_UNION_V1','composition','primitives.program.compose_masks',{'operation':'union','color_policy':'same_color_or_invalid'}),_s('COMP_MASK_INTERSECTION_V1','composition','primitives.program.compose_masks',{'operation':'intersection','color_policy':'same_color_or_invalid'}),_s('COMP_MASK_DIFF_A_B_V1','composition','primitives.program.compose_masks',{'operation':'difference_a_b','color_policy':'source_color'}),_s('COMP_MASK_DIFF_B_A_V1','composition','primitives.program.compose_masks',{'operation':'difference_b_a','color_policy':'source_color'}),_s('COPY_RELATIVE_REFERENCE_V1','composition','primitives.program.copy_relative',{'axis':'row|column','gap':'int','edge':'top|bottom|left|right'})]
_PAT=[_s('PAT_FIND_ROW_PERIOD_V1','pattern','patterns.core.smallest_period',semantics='Returns the smallest positive cell period compatible with observed sequence positions; it is not inferred merely from divisibility.'),_s('PAT_FIND_COLUMN_PERIOD_V1','pattern','patterns.core.smallest_period'),_s('PAT_FIND_2D_TILE_PERIOD_V1','pattern','patterns.core.tile_period'),_s('PAT_FIND_COLOR_RUN_PERIOD_V1','pattern','patterns.core.smallest_period'),_s('PAT_EXTEND_ROW_V1','pattern','patterns.core.complete_rows'),_s('PAT_EXTEND_COLUMN_V1','pattern','patterns.core.complete_columns'),_s('PAT_COMPLETE_ROW_PERIOD_V1','pattern','patterns.core.complete_rows'),_s('PAT_COMPLETE_COLUMN_PERIOD_V1','pattern','patterns.core.complete_columns'),_s('PAT_COMPLETE_2D_TILE_V1','pattern','patterns.core.tile_period'),_s('PAT_REPAIR_PERIOD_VIOLATION_V1','pattern','patterns.core.repair_rows',semantics='Repairs only cells disagreeing with a supported period template.'),_s('PAT_COMPLETE_MIRROR_HORIZONTAL_V1','pattern','patterns.core.symmetry_complete'),_s('PAT_COMPLETE_MIRROR_VERTICAL_V1','pattern','patterns.core.symmetry_complete'),_s('PAT_COMPLETE_MIRROR_DIAGONAL_MAIN_V1','pattern','patterns.core.symmetry_complete'),_s('PAT_COMPLETE_MIRROR_DIAGONAL_ANTI_V1','pattern','patterns.core.symmetry_complete'),_s('PAT_FIND_PERIOD_VIOLATIONS_V1','pattern','patterns.core.repair_rows'),_s('PAT_FIND_SYMMETRY_VIOLATIONS_V1','pattern','patterns.core.symmetry_complete')]
_CAP=[_s('REG_FIND_REGIONS_4_V1','region','capabilities.regions.regions',{'connectivity':4}),_s('REG_FIND_REGIONS_8_V1','region','capabilities.regions.regions',{'connectivity':8}),_s('REG_FIND_ENCLOSED_REGIONS_V1','region','capabilities.regions.enclosed_regions'),_s('REG_FIND_HOLES_V1','region','capabilities.regions.find_holes'),_s('REG_FLOOD_FILL_V1','region','capabilities.regions.fill_interior'),_s('REG_FILL_INTERIOR_V1','region','capabilities.regions.fill_interior'),_s('COUNT_OBJECTS_V1','count','capabilities.counting.count_objects'),_s('COUNT_COLOR_CELLS_V1','count','capabilities.counting.count_color_cells'),_s('COUNT_RUNS_V1','count','capabilities.counting.count_runs'),_s('GEN_N_CELLS_ROW_V1','generation','capabilities.generation.n_cells_row'),_s('GEN_N_CELLS_COLUMN_V1','generation','capabilities.generation.n_cells_column')]
_CAP += [_s('LINE_FIND_FULL_HORIZONTAL_V1','line','capabilities.lines.full_horizontal'),_s('LINE_FIND_FULL_VERTICAL_V1','line','capabilities.lines.full_vertical'),_s('SEG_SPLIT_BY_SEPARATOR_V1','line','capabilities.lines.split_separator'),_s('GRAPH_FROM_OBJECT_PIXELS_4_V1','graph','capabilities.paths.graph_pixels'),_s('GRAPH_FIND_ENDPOINTS_V1','graph','capabilities.paths.endpoints'),_s('GRAPH_FIND_BRANCH_NODES_V1','graph','capabilities.paths.branches'),_s('GRAPH_IS_SIMPLE_PATH_V1','graph','capabilities.paths.simple_path'),_s('GRAPH_TRACE_PATH_V1','graph','capabilities.paths.trace'),_s('GEN_RECTANGLE_V1','generation','capabilities.generation.rectangle'),_s('GEN_FILLED_RECTANGLE_V1','generation','capabilities.generation.rectangle')]
_CAP += [_s('REG_INTERIOR_MASK_V1','region','capabilities.regions.interior_mask'),_s('REG_EXTERIOR_MASK_V1','region','capabilities.regions.exterior_mask'),_s('REG_REGION_BOUNDARY_V1','region','capabilities.regions.region_boundary'),_s('REG_REGION_ADJACENCY_V1','region','capabilities.regions.adjacent_regions'),_s('LINE_FIND_PARTIAL_HORIZONTAL_V1','line','capabilities.lines.partial_horizontal'),_s('LINE_FIND_PARTIAL_VERTICAL_V1','line','capabilities.lines.partial_vertical'),_s('SEQ_GRID_TO_ROW_V1','sequence','capabilities.sequence.grid_row'),_s('SEQ_GRID_TO_COLUMN_V1','sequence','capabilities.sequence.grid_column'),_s('SEQ_TO_ROW_GRID_V1','sequence','capabilities.sequence.sequence_row'),_s('SEQ_TO_COLUMN_GRID_V1','sequence','capabilities.sequence.sequence_column'),_s('SEQ_REVERSE_V1','sequence','capabilities.sequence.reverse'),_s('SEQ_REPEAT_V1','sequence','capabilities.sequence.repeat')]
_CAP += [_s('ITERATE_TRANSLATE_BOUNDED_V1','iteration','capabilities.iteration.repeat_translation'),_s('LINE_EXTEND_UNTIL_BOUNDARY_V1','iteration','capabilities.iteration.extend_line_until_boundary')]
_CAP += [
 _s('REG_EXTRACT_REGION_AT_V1','region','capabilities.regions.extract_region_at',{'row':'int','col':'int','connectivity':'4|8'}),
 _s('LINE_CONNECT_ALIGNED_POINTS_V1','line','capabilities.lines.connect_aligned_points',{'first':'Coordinate','second':'Coordinate','color':'0..9 optional'}),
 _s('GRAPH_IS_CONNECTED_V1','graph','capabilities.paths.connected'),
 _s('GRAPH_SHORTEST_PATH_V1','graph','capabilities.paths.shortest_path',{'start':'Coordinate','end':'Coordinate'}),
 _s('PATH_COLOR_SEQUENCE_V1','sequence','capabilities.paths.path_color_sequence',{'path':'Path'}),
 _s('PATH_SERIALIZE_ROW_V1','sequence','capabilities.sequence.sequence_row'),
 _s('PATH_SERIALIZE_COLUMN_V1','sequence','capabilities.sequence.sequence_column'),
 _s('COUNT_REGIONS_V1','count','capabilities.counting.count_regions',{'connectivity':'4|8','color':'0..9 optional'}),
 _s('COUNT_SELECTED_REGION_AREA_V1','count','capabilities.counting.selected_region_area'),
 _s('COUNT_VALUE_FREQUENCY_V1','count','capabilities.counting.value_frequency'),
 _s('COUNT_REPEATED_MOTIF_V1','count','capabilities.counting.repeated_motif_count',{'motif':'Sequence'}),
 _s('GEN_SOLID_ROW_V1','generation','capabilities.generation.solid_row',{'row':'int','color':'0..9','shape':'GridShape optional'}),
 _s('GEN_SOLID_COLUMN_V1','generation','capabilities.generation.solid_column',{'col':'int','color':'0..9','shape':'GridShape optional'}),
 _s('GEN_MASK_TO_GRID_V1','generation','capabilities.generation.mask_to_grid',{'color':'0..9','background':'0..9 optional'}),
 _s('GEN_REPEAT_MASK_V1','generation','capabilities.generation.repeat_mask',{'anchors':'Coordinate[]','color':'0..9','shape':'GridShape optional','background':'0..9 optional'}),
 _s('SEQ_RUN_LENGTH_ENCODE_V1','sequence','capabilities.sequence.run_length_encode'),
]
REGISTRY={spec.primitive_id:spec for spec in (_BASE+_SELECT+_REL_SPECS+_OPS+_PAT+_CAP)}
def validate_registry(registry=REGISTRY)->list[str]:
    errors=[]
    if len(registry)!=len(set(registry)): errors.append('duplicate primitive id')
    for identifier,spec in registry.items():
        data=spec.json()
        if set(data) < REQUIRED_FIELDS: errors.append(f'{identifier}: missing metadata')
        if identifier!=spec.primitive_id or not identifier.endswith(('_V0','_V1')): errors.append(f'{identifier}: invalid semantic id')
        module,_,attr=spec.implementation_reference.rpartition('.')
        try: getattr(importlib.import_module(module),attr)
        except (ImportError,AttributeError): errors.append(f'{identifier}: missing implementation')
        if not isinstance(spec.input_types,list) or not isinstance(spec.output_types,list) or not isinstance(spec.parameters,dict): errors.append(f'{identifier}: invalid schema type')
    return errors
